<?php
/*
** ATMOCOM weather data CSV/JSON/XML formatter
** This script will load latest current and cumulative data from a data file generated by atmolog.php.
** Data output is formatted in CSV, JSON or XML format. In default configuration with no file
** path specified, this script must be placed in the same directory as atmolog.php
**
** NOTE! CSV field specification can be found at the end of this file
**
** Requires URL parameter 'id' which is the Weather Underground station name in lower case letters, e.g. ibenalmd17
** For CSV formatting: http://www.mysite.com/wxloader.php?id=ibenalmd17&format=c
** For JSON formatting: http://www.mysite.com/wxloader.php?id=ibenalmd17&format=j
** For XML formatting: http://www.mysite.com/wxloader.php?id=ibenalmd17&format=x
**
** NOTE! XML formatting is an ***experimental*** PHP feature and requires PHP module xmlrpc to be enabled
**
** License
** Original code (c)2019 Astrogenic Systems -- permission is hereby granted to modify and redistribute
** modified versions of this file freely as long as it is made clear that the modified file is not the 
** original. Support for any derivative code is to be provided by the author. Astrogenic Systems 
** copyright claim must remain, author may add own copyright for modified portions of code.
*/

/*
 Below is the only parameter that needs configuring.
 Set it to point to directory where station 
 data file (e.g. ibenalmd17_data.txt) is located.
 Leave empty if data file and this script are
 in the same directory
*/
$wxdata_dir = "";


// ***** No need to change anything below this line! *****
$station_id = "";

if (array_key_exists('fmt', $_REQUEST)) $format=$_REQUEST['fmt'];
else $format="j";

if (array_key_exists('id', $_REQUEST)) $station_id=$_REQUEST['id'];
else die();

$data = load_data($wxdata_dir, $station_id);

//3 possible output formats, c=csv, j=json or x=xml
if($format === "c")
{
    if(count($data[0]) > 0)
    {
        $csv_sep = ",";
        $merged_data = $data[0] + $data[1];
        echo implode($csv_sep, $merged_data);
    }
    else die("Error: No data");
}
else if ($format === "j" || $format === "x")
{
    if(count($data[0]) > 0)
    {
        if($format === "j") echo json_encode($data, JSON_PRETTY_PRINT );
        else {
            //Change NULL values to 0 otherwise XML will be malformed
            $data2 = array_map(function($value) {
                return empty($value) ? "0" : $value;
            }, $data[0]); // array_map should walk through $data array
            
            $data2+=$data[1];
            echo xmlrpc_encode($data2);
        }
    }
    else die("Error: No data");
}
else die("Error: Argument error");

function load_data($dir, $station_id)
{
    $dateFormat = "Y-m-d";
    $timeFormat = "H:i:s";
    $timeFormatS = "H:i";

    $data_arr = array();
    $data_arr[0] = array();
    $data_arr[1] = array();

    $station_wxfile = $station_id . "_data.txt";
    if(strlen($dir) > 0) $station_wxfile = $dir . "/" . $station_wxfile;

    //Check that file exists and has data in it
    if(file_exists($station_wxfile)) 
    {
        $fstr = file_get_contents($station_wxfile);
    }
    else {
        die("File load error: Cannot find or open <strong>" .$station_wxfile . "</strong>!");
    }

    if(strlen($fstr) === 0) {
        die("Data parse error: File is empty!");
    }

    $farr = explode(PHP_EOL, $fstr);
    foreach($farr as $ln)
    {
        if(isValidData($ln))
        {
            $data = explode(":", $ln);
            if(strcmp($data[0], "stamp") === 0)
            {
                $data_arr[0]['ID'] = $data[1];
                $data_arr[0]['STATIONID'] = $data[6];

                $data_arr[0]['DATE'] = date($dateFormat, $data[2]);
                $data_arr[0]['TIME'] = date($timeFormat, $data[2]);
                $data_arr[0]['TEMP_UNIT'] = $data[7];
                $data_arr[0]['PRESS_UNIT'] = $data[8];
                $data_arr[0]['RAIN_UNIT'] = $data[9];
                $data_arr[0]['FIRMWARE_REV'] = $data[10];
            }
            else if(strcmp($data[0], "wind") === 0)
            {
                $data_arr[0]['WINDDIR'] = $data[1];
                $data_arr[0]['WINDVEL'] = $data[2];
                $data_arr[0]['WGUSTDIR'] = $data[3];
                $data_arr[0]['WINDGUSTVEL'] = $data[4];
                $data_arr[1]['WDIR_AVG'] = $data[5];
            }            
            else if(strcmp($data[0], "otemp") === 0)
            {
                $data_arr[0]['TEMP'] = $data[1];
                $data_arr[1]['TEMP_MAX'] = $data[2];
                $data_arr[1]['TEMP_MIN'] = $data[3];
                $data_arr[1]['TEMP_MAXTIME'] = date($timeFormatS, $data[4]);
                $data_arr[1]['TEMP_MINTIME'] = date($timeFormatS, $data[5]);
                $data_arr[1]['TEMP_TREND'] = $data[6];
            }
            else if(strcmp($data[0], "baro") === 0)
            {
                $data_arr[0]['BARO'] = $data[1];
                $data_arr[1]['BARO_MAX'] = $data[2];
                $data_arr[1]['BARO_MIN'] = $data[3];
                $data_arr[1]['BARO_MAXTIME'] = date($timeFormatS, $data[4]);
                $data_arr[1]['BARO_MINTIME'] = date($timeFormatS, $data[5]);
                $data_arr[1]['BARO_TREND'] = $data[6];
            }            
            else if(strcmp($data[0], "precip") === 0)
            {
                $data_arr[0]['PRECIP'] = $data_arr[1]['RAIN_RATE'] = $data[1];
                $data_arr[0]['PRECIPDAY'] = $data_arr[1]['RAIN_TODAY'] = $data[2];
                $data_arr[1]['RAIN_YESTERDAY'] = $data[3];
                $data_arr[1]['RAIN_WEEK'] = $data[4];
                $data_arr[1]['RAIN_MONTH'] = $data[5];
                $data_arr[1]['RAIN_YEAR'] = $data[6];
            }
            else if(strcmp($data[0], "itemp") === 0)
            {
                $data_arr[0]['INTEMP'] = $data[1];
            }
            else if(strcmp($data[0], "dewpt") === 0)
            {
                $data_arr[0]['DEWPT'] = $data[1];
            }
            else if(strcmp($data[0], "rhum") === 0)
            {
                $data_arr[0]['RHUM'] = $data[1];
            }
            else if(strcmp($data[0], "ihum") === 0)
            {
                $data_arr[0]['INRHUM'] = $data[1];
            }
            else if(strcmp($data[0], "uvsol") === 0)
            {
                $data_arr[0]['UVIDX'] = $data[1];
                $data_arr[0]['SOLAR'] = $data[2];
            }
        }
    } //foreach

    return $data_arr;
}

function isValidData($str)
{
	return (strlen($str) > 0 && $str[0] !== '#');
}

/*
=== CSV fields in order from left to right ===
Field name			Description
------------------------------------------------------------
ID 					sequential update counter
STATIONID 			Weather Underground station name
DATE				Date (YYYY-MM-DD) of last update
TIME				Time (HH:MM:SS) of last update
TEMP_UNIT 			C or F
PRESS_UNIT 			hPa or inHg
RAIN_UNIT 			mm or in
FIRMWARE_REV 		ATMOCOM installed firmware version
WINDDIR				wind direction
WINDVEL				wind speed
WGUSTDIR			wind gust direction
WINDGUSTVEL			wind gust speed
TEMP				outdoor temperature
INTEMP 				indoor temperature
DEWPT				dewpoint
RHUM				relative hunidity
INRHUM 				indoor humidity
BARO				barometric pressure (relative)
UVIDX				UV index
SOLAR				solar radiation W/m2
PRECIP 				rain rate
PRECIPDAY 			total rain today
WDIR_AVG 			average wind direction
TEMP_MAX 			max temperature today
TEMP_MIN 			min temperature today
TEMP_MAXTIME 		time of max temp
TEMP_MINTIME 		time of min temp
TEMP_TREND 			temperature trend, positive or negative
BARO_MAX 			max barometric pressure today
BARO_MIN 			min barometric pressure today
BARO_MAXTIME 		time of max barometric pressure
BARO_MINTIME 		time of min barometric pressure
BARO_TREND 			pressure trend, positive or negative
RAIN_RATE 			same as PRECIP
RAIN_TODAY 			same as PRECIPDAY
RAIN_YESTERDAY 		total rain yesterday
RAIN_WEEK			total rain this week
RAIN_MONTH 			total rain current month
RAIN_YEAR 			total rain current year
*/
?>